name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      # Repository auschecken, damit Workflow es nutzen kann
      - uses: actions/checkout@v3

      # Mit Pandoc README.md in README.pdf umwandeln
      # args werden an pandoc-Befehl angehängt
      - uses: docker://pandoc/latex
        with:
          args: "README.md -o README.pdf"

      # Geänderte Datein zurück ins Repository committen
      - uses: stefanzweifel/git-auto-commit-action@v4
